services:
  - type: web
    name: soccer-field-directory-server
    env: node
    buildCommand: 'npm install'
    startCommand: 'node app.js'
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: soccer-field-db
          property: connectionString
